web:
  image: pdxjohnny/textbooks-server
  ports:
    - "8080:8080"
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=testdb
